version: '3'
volumes:
  db:
  gems:
  redis:
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
  app:
    build: .
    command: foreman start -p 3000
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db
      - redis
    env_file:
      - .env
